// This configuration is public and can be safely used in the client
// This is automatically generated by the backend, do not edit
export const firebaseConfig = {
  apiKey: 'AIzaSyBe_eLsxwn_gZ1C1zR-HnC5p12c-g4KBEI',
  authDomain: 'againstme-44f13.firebaseapp.com',
  projectId: 'againstme-44f13',
  storageBucket: 'againstme-44f13.appspot.com',
  messagingSenderId: '36730034239',
  appId: '1:36730034239:web:545d1ff3945897c72f77c3'
};
