// This configuration is public and can be safely used in the client
// This is automatically generated by the backend, do not edit
export const firebaseConfig = {
  apiKey: "AIzaSyAq0xLOfDq_UGCEG3i3CW6gjVUi9D8Fkro",
  authDomain: "studio-5327904560-35732.firebaseapp.com",
  projectId: "studio-5327904560-35732",
  storageBucket: "studio-5327904560-35732.appspot.com",
  messagingSenderId: "78243284867",
  appId: "1:78243284867:web:3f1e83343620704245d8b6"
};
