// This configuration is public and can be safely used in the client
// This is automatically generated by the backend, do not edit
export const firebaseConfig = {
  apiKey: "AIzaSyAW2EbF9GWdf6oj7k6FkwvOcKGm1UTCJh0",
  authDomain: "againstme-44f13.firebaseapp.com",
  projectId: "againstme-44f13",
  storageBucket: "againstme-44f13.firebasestorage.app",
  messagingSenderId: "952087025637",
  appId: "1:952087025637:web:f52616d268a19014dd410c",
  measurementId: "G-Q5GWNNJ2MG"
};
